modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

issueTrackerURL = "https://github.com/Minecraft269/ClientTimeAndWeatherControlMod/issues"

[[mods]]
modId="clienttimeandweathercontrolmod"
version="${mod_version}"
displayName="ClientTimeAndWeatherControlMod"
description="Modifies the time and sky for the client"
authors="Minecraft269"

[[dependencies.clienttimeandweathercontrolmod]]
modId="forge"
versionRange="${forge_version_range}"
mandatory=true

[[dependencies.clienttimeandweathercontrolmod]]
modId="minecraft"
versionRange="${minecraft_version_range}"
mandatory=true

[[dependencies.clienttimeandweathercontrolmod]]
modId="cloth_config"
versionRange="${cloth_config_version_range}"
mandatory=true

[modproperties.clienttimeandweathercontrolmod]
badges=["client"]
links=["modmenu.modrinth=https://modrinth.com/project/bJBWxhMB",
       "modmenu.mcmod=https://www.mcmod.cn/class/21836.html",
       "modmenu.github=https://github.com/Minecraft269/ClientTimeAndWeatherControlMod"
]
